//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTROS_INVENTARIO
    {
        public int ID { get; set; }
        public string ACCION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> ID_SERVICIO { get; set; }
    
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
