//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_COMPRAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTRO_COMPRAS()
        {
            this.CLIENTES_ATENDIDOS = new HashSet<CLIENTES_ATENDIDOS>();
        }
    
        public int ID_COMPRA { get; set; }
        public string CEDULA_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string CORREO { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> TOTAL_COMPRA { get; set; }
        public int ID_EMPLEADO { get; set; }
        public string NOMBRE_EMPLEADO { get; set; }
        public Nullable<int> ID_METODO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTES_ATENDIDOS> CLIENTES_ATENDIDOS { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual METODOS_PAGO METODOS_PAGO { get; set; }
    }
}
