//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public int ID_ROL { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ID_SERVICIO { get; set; }
    
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
